name: check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: yarn install
        run: yarn install
      - name: yarn lint
        run: yarn lint
      - name: yarn test
        run: yarn test --passWithNoTests
      - name: yarn build
        run: yarn build
  deploy_for_preview:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - name: Firebase Preview Deploy
        if: ${{ github.repository_owner == 'tomoeine' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIFE_PG }}"
          expires: 10d
          projectId: life-progress
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
