name: firebase-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - name: Firebase Production Deploy
        run: yarn deploy --token=${{ secrets.FIREBASE_TOKEN }}
